# Introduction {.unnumbered}

This is a textbook to learn how to analyze cultural phenomena using computational methods.

It follows the principles of Open Science to teach you how to conduct research that is ethical, methodologically solid, and accessible. Topics covered include:

-   theory development
-   data management
-   data collection
-   data analysis
-   data visualization.

We believe that none of these aspects should be disregarded in a cultural analytics project that aims at being truly Open.

The programming language used is Python. There are discursive sections and interactive Jupyter Notebooks to let you learn-by-doing.

------------------------------------------------------------------------

This work, created by Federico Pianzola and  Paschalis Agapitos, and with the University of Groningen as the copyright holder, is licensed under a [CC BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/).

Some of the pages of this guide have been originally created by others and authorship is attributed on indivdual pages:

- [The Turing Way](https://the-turing-way.netlify.app/welcome.html) handbook to reproducible, ethical and collaborative data science, initiated by The Alan Turing Institute, licensed under [CC BY 4.0 License](https://creativecommons.org/licenses/by/4.0/)
- [Introduction to Cultural Analytics & Python](https://melaniewalsh.github.io/Intro-Cultural-Analytics/welcome.html) by Melanie Walsh, licensed under [CC BY-NC-SA 4.0 License](https://creativecommons.org/licenses/by-nc-sa/4.0/)

This is a Quarto book created from markdown and executable code.

To learn more about Quarto books visit <https://quarto.org/docs/books>.
